export const actionTypes = {
    LOGIN_USER_METHOD: "login_user_method",
    LOGOUT_USER_METHOD: "logout_user_method",
    SAVE_USER_DATA: "save_user_data",

    CHANGE_APP_LANGUAGE: "CHANGE_APP_LANGUAGE",
    CHANGE_APP_SAFE_AREA_VIEW_COLOR: "CHANGE_APP_SAFE_AREA_VIEW_COLOR",

    UPDATE_USER_METHOD: "update_user_method",
    UPDATE_USER_SUCCESS: "update_user_success",
    UPDATE_USER_FAIL: "update_user_fail",
    UPDATE_USER_CLEAR: "update_user_clear",

    CHANGE_PASSWORD_METHOD: "CHANGE_PASSWORD_METHOD",
    CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
    CHANGE_PASSWORD_FAIL: "CHANGE_PASSWORD_FAIL",
    CHANGE_PASSWORD_CLEAR: "CHANGE_PASSWORD_CLEAR",

    HOME_BANNER_METHOD: "HOME_BANNER_METHOD",
    HOME_BANNER_SUCCESS: "HOME_BANNER_SUCCESS",
    HOME_BANNER_FAIL: "HOME_BANNER_FAIL",
    HOME_BANNER_CLEAR: "HOME_BANNER_CLEAR",

    FEATURED_SERVICE_CATEGORY_METHOD: "FEATURED_SERVICES_METHOD",
    FEATURED_SERVICE_CATEGORY_SUCCESS: "FEATURED_SERVICES_SUCCESS",
    FEATURED_SERVICE_CATEGORY_FAIL: "FEATURED_SERVICES_FAIL",
    FEATURED_SERVICE_CATEGORY_CLEAR: "FEATURED_SERVICES_CLEAR",

    SERVICE_CATEGORY_METHOD: "SERVICE_CATEGORY_METHOD",
    SERVICE_CATEGORY_SUCCESS: "SERVICE_CATEGORY_SUCCESS",
    SERVICE_CATEGORY_FAIL: "SERVICE_CATEGORY_FAIL",
    SERVICE_CATEGORY_CLEAR: "SERVICE_CATEGORY_CLEAR",

    SERVICES_METHOD: "SERVICES_METHOD",
    SERVICES_SUCCESS: "SERVICES_SUCCESS",
    SERVICES_FAIL: "SERVICES_FAIL",
    SERVICES_CLEAR: "SERVICES_CLEAR",

    SERVICES_SESSION_DATES_METHOD: "SERVICES_SESSION_DATES_METHOD",
    SERVICES_SESSION_DATES_SUCCESS: "SERVICES_SESSION_DATES_SUCCESS",
    SERVICES_SESSION_DATES_FAIL: "SERVICES_SESSION_DATES_FAIL",
    SERVICES_SESSION_DATES_CLEAR: "SERVICES_SESSION_DATES_CLEAR",

    SERVICES_SESSION_METHOD: "SERVICES_SESSION_METHOD",
    SERVICES_SESSION_SUCCESS: "SERVICES_SESSION_SUCCESS",
    SERVICES_SESSION_FAIL: "SERVICES_SESSION_FAIL",
    SERVICES_SESSION_CLEAR: "SERVICES_SESSION_CLEAR",

    SERVICES_SESSION_SLOTS_METHOD: "SERVICES_SESSION_SLOTS_METHOD",
    SERVICES_SESSION_SLOTS_SUCCESS: "SERVICES_SESSION_SLOTS_SUCCESS",
    SERVICES_SESSION_SLOTS_FAIL: "SERVICES_SESSION_SLOTS_FAIL",
    SERVICES_SESSION_SLOTS_CLEAR: "SERVICES_SESSION_SLOTS_CLEAR",

    ADD_SERVICE_INTO_CART_METHOD: "ADD_SERVICE_INTO_CART_METHOD",
    REMOVE_SERVICE_FROM_CART_METHOD: "REMOVE_SERVICE_FROM_CART_METHOD",
    PLUS_SERVICE_QUANTITY_IN_CART_METHOD: "PLUS_SERVICE_QUANTITY_IN_CART_METHOD",
    MINUS_SERVICE_QUANTITY_IN_CART_METHOD: "MINUS_SERVICE_QUANTITY_IN_CART_METHOD",

    GET_MY_ADDRESS_METHOD: "GET_MY_ADDRESS_METHOD",
    GET_MY_ADDRESS_SUCCESS: "GET_MY_ADDRESS_SUCCESS",
    GET_MY_ADDRESS_PAGINATION_SUCCESS: "GET_MY_ADDRESS_PAGINATION_SUCCESS",
    GET_MY_ADDRESS_FAIL: "GET_MY_ADDRESS_FAIL",
    GET_MY_ADDRESS_CLEAR: "GET_MY_ADDRESS_CLEAR",

    GET_HOME_SUGGESTION_METHOD: "GET_HOME_SUGGESTION_METHOD",
    GET_HOME_SUGGESTION_SUCCESS: "GET_HOME_SUGGESTION_SUCCESS",
    GET_HOME_SUGGESTION_FAIL: "GET_HOME_SUGGESTION_FAIL",
    GET_HOME_SUGGESTION_CLEAR: "GET_HOME_SUGGESTION_CLEAR",

    GET_MY_UPCOMING_BOOKING_METHOD: "GET_MY_UPCOMING_BOOKING_METHOD",
    GET_MY_UPCOMING_BOOKING_SUCCESS: "GET_MY_UPCOMING_BOOKING_SUCCESS",
    GET_MY_UPCOMING_BOOKING_FAIL: "GET_MY_UPCOMING_BOOKING_FAIL",
    GET_MY_UPCOMING_BOOKING_CLEAR: "GET_MY_UPCOMING_BOOKING_CLEAR",
    GET_MY_UPCOMING_BOOKING_PAGINATION_SUCCESS: "GET_MY_UPCOMING_BOOKING_PAGINATION_SUCCESS",

    GET_MY_PAST_BOOKING_METHOD: "GET_MY_PAST_BOOKING_METHOD",
    GET_MY_PAST_BOOKING_SUCCESS: "GET_MY_PAST_BOOKING_SUCCESS",
    GET_MY_PAST_BOOKING_FAIL: "GET_MY_PAST_BOOKING_FAIL",
    GET_MY_PAST_BOOKING_CLEAR: "GET_MY_PAST_BOOKING_CLEAR",
    GET_MY_PAST_BOOKING_PAGINATION_SUCCESS: "GET_MY_PAST_BOOKING_PAGINATION_SUCCESS",

    GET_SERVICE_BOOKING_PROMOCODE_LIST_METHOD: "GET_SERVICE_BOOKING_PROMOCODE_LIST_METHOD",
    GET_SERVICE_BOOKING_PROMOCODE_LIST_SUCCESS: "GET_SERVICE_BOOKING_PROMOCODE_LIST_SUCCESS",
    GET_SERVICE_BOOKING_PROMOCODE_LIST_FAIL: "GET_SERVICE_BOOKING_PROMOCODE_LIST_FAIL",
    GET_SERVICE_BOOKING_PROMOCODE_LIST_CLEAR: "GET_SERVICE_BOOKING_PROMOCODE_LIST_CLEAR",

    GET_FAQS_METHOD: "GET_FAQS_METHOD",
    GET_FAQS_SUCCESS: "GET_FAQS_SUCCESS",
    GET_FAQS_FAIL: "GET_FAQS_FAIL",
    GET_FAQS_CLEAR: "GET_FAQS_CLEAR",
    GET_FAQS_PAGINATION_SUCCESS: "GET_FAQS_PAGINATION_SUCCESS",

    GET_NOTIFICATION_METHOD: "GET_NOTIFICATION_METHOD",
    GET_NOTIFICATION_SUCCESS: "GET_NOTIFICATION_SUCCESS",
    GET_NOTIFICATION_PAGINATION_SUCCESS: "GET_NOTIFICATION_PAGINATION_SUCCESS",
    GET_NOTIFICATION_FAIL: "GET_NOTIFICATION_FAIL",
    GET_NOTIFICATION_CLEAR: "GET_NOTIFICATION_CLEAR",
}